// Mock agent data for the Bookooda search page
export const agents = [
    {
        id: 1,
        name: 'VisaPro Consultants',
        city: 'Lahore',
        coordinates: { lat: 31.5204, lng: 74.3587 },
        rating: 4.8,
        reviews: 342,
        experience: '8 Years',
        services: ['Germany Visa', 'UK Study Visa', 'Canada PR'],
        tags: ['Visa Expert'],
        startingPrice: 25000,
        avatar: 'VP',
        verified: true,
    },
    {
        id: 2,
        name: 'Global Study Hub',
        city: 'Islamabad',
        coordinates: { lat: 33.6844, lng: 73.0479 },
        rating: 4.9,
        reviews: 218,
        experience: '12 Years',
        services: ['UK Study Visa', 'Australia Study', 'Canada Study'],
        tags: ['Study Consultant'],
        startingPrice: 30000,
        avatar: 'GS',
        verified: true,
    },
    {
        id: 3,
        name: 'TravelEase Pakistan',
        city: 'Karachi',
        coordinates: { lat: 24.8607, lng: 67.0011 },
        rating: 4.7,
        reviews: 189,
        experience: '6 Years',
        services: ['Flight Booking', 'Hotel Reservation', 'Travel Insurance'],
        tags: ['Travel Agent'],
        startingPrice: 5000,
        avatar: 'TE',
        verified: true,
    },
    {
        id: 4,
        name: 'UK Dreams Education',
        city: 'Rawalpindi',
        coordinates: { lat: 33.5651, lng: 73.0169 },
        rating: 4.6,
        reviews: 156,
        experience: '5 Years',
        services: ['UK Study Visa', 'Ireland Study', 'IELTS Prep'],
        tags: ['Study Consultant'],
        startingPrice: 35000,
        avatar: 'UD',
        verified: true,
    },
    {
        id: 5,
        name: 'SafarNama Tours',
        city: 'Lahore',
        coordinates: { lat: 31.4697, lng: 74.4100 },
        rating: 4.5,
        reviews: 278,
        experience: '10 Years',
        services: ['Umrah Visa', 'Flight Booking', 'Hotel Reservation'],
        tags: ['Umrah Specialist'],
        startingPrice: 15000,
        avatar: 'SN',
        verified: true,
    },
    {
        id: 6,
        name: 'EuroVisa Solutions',
        city: 'Faisalabad',
        coordinates: { lat: 31.4504, lng: 73.1350 },
        rating: 4.8,
        reviews: 134,
        experience: '7 Years',
        services: ['Germany Visa', 'Schengen Visa', 'Italy Visa'],
        tags: ['Visa Expert'],
        startingPrice: 20000,
        avatar: 'EV',
        verified: true,
    },
    {
        id: 7,
        name: 'Canada Gate Immigration',
        city: 'Islamabad',
        coordinates: { lat: 33.7294, lng: 73.0931 },
        rating: 4.9,
        reviews: 412,
        experience: '15 Years',
        services: ['Canada PR', 'Canada Study', 'Canada Appointment Booking'],
        tags: ['Immigration Expert'],
        startingPrice: 50000,
        avatar: 'CG',
        verified: true,
    },
    {
        id: 8,
        name: 'Al-Haram Travel Agency',
        city: 'Multan',
        coordinates: { lat: 30.1575, lng: 71.5249 },
        rating: 4.7,
        reviews: 523,
        experience: '20 Years',
        services: ['Umrah Visa', 'Hajj Packages', 'Flight Booking'],
        tags: ['Umrah Specialist'],
        startingPrice: 12000,
        avatar: 'AH',
        verified: true,
    },
    {
        id: 9,
        name: 'SwiftFly Travels',
        city: 'Karachi',
        coordinates: { lat: 24.9056, lng: 67.0822 },
        rating: 4.4,
        reviews: 97,
        experience: '3 Years',
        services: ['Flight Booking', 'Hotel Reservation', 'Travel Insurance'],
        tags: ['Travel Agent'],
        startingPrice: 3000,
        avatar: 'SF',
        verified: false,
    },
    {
        id: 10,
        name: 'AussiePath Consultants',
        city: 'Lahore',
        coordinates: { lat: 31.5497, lng: 74.3436 },
        rating: 4.6,
        reviews: 167,
        experience: '9 Years',
        services: ['Australia Study', 'Australia PR', 'Australia Visa'],
        tags: ['Study Consultant'],
        startingPrice: 40000,
        avatar: 'AP',
        verified: true,
    },
    {
        id: 11,
        name: 'InsureTravel PK',
        city: 'Islamabad',
        coordinates: { lat: 33.6995, lng: 73.0363 },
        rating: 4.3,
        reviews: 89,
        experience: '4 Years',
        services: ['Travel Insurance', 'Health Insurance', 'Visa Insurance'],
        tags: ['Insurance Provider'],
        startingPrice: 2500,
        avatar: 'IT',
        verified: true,
    },
    {
        id: 12,
        name: 'Turkey Visa Center',
        city: 'Peshawar',
        coordinates: { lat: 34.0151, lng: 71.5249 },
        rating: 4.7,
        reviews: 201,
        experience: '6 Years',
        services: ['Turkey Visa', 'Turkey Study', 'Appointment Booking'],
        tags: ['Visa Expert'],
        startingPrice: 15000,
        avatar: 'TV',
        verified: true,
    },
    {
        id: 13,
        name: 'DreamAbroad Academy',
        city: 'Sialkot',
        coordinates: { lat: 32.4945, lng: 74.5229 },
        rating: 4.5,
        reviews: 112,
        experience: '5 Years',
        services: ['Germany Study', 'UK Study Visa', 'Scholarship Guidance'],
        tags: ['Study Consultant'],
        startingPrice: 28000,
        avatar: 'DA',
        verified: true,
    },
    {
        id: 14,
        name: 'FlyStar Aviation',
        city: 'Karachi',
        coordinates: { lat: 24.8719, lng: 66.9888 },
        rating: 4.8,
        reviews: 367,
        experience: '11 Years',
        services: ['Flight Booking', 'Group Flights', 'Corporate Travel'],
        tags: ['Flight Specialist'],
        startingPrice: 8000,
        avatar: 'FS',
        verified: true,
    },
    {
        id: 15,
        name: 'SchengenPro Services',
        city: 'Lahore',
        coordinates: { lat: 31.4826, lng: 74.3325 },
        rating: 4.9,
        reviews: 289,
        experience: '10 Years',
        services: ['Schengen Visa', 'France Visa', 'Spain Visa'],
        tags: ['Visa Expert'],
        startingPrice: 22000,
        avatar: 'SP',
        verified: true,
    },
    {
        id: 16,
        name: 'Naya Safar Travels',
        city: 'Quetta',
        coordinates: { lat: 30.1798, lng: 66.9750 },
        rating: 4.2,
        reviews: 64,
        experience: '4 Years',
        services: ['Iran Visa', 'Flight Booking', 'Hotel Reservation'],
        tags: ['Travel Agent'],
        startingPrice: 5000,
        avatar: 'NS',
        verified: false,
    },
    {
        id: 17,
        name: 'MedInsure Travel',
        city: 'Rawalpindi',
        coordinates: { lat: 33.5920, lng: 73.0488 },
        rating: 4.6,
        reviews: 143,
        experience: '7 Years',
        services: ['Travel Insurance', 'Medical Insurance', 'Visa Insurance'],
        tags: ['Insurance Provider'],
        startingPrice: 3500,
        avatar: 'MI',
        verified: true,
    },
    {
        id: 18,
        name: 'StayWorld Hotels',
        city: 'Islamabad',
        coordinates: { lat: 33.7104, lng: 73.0579 },
        rating: 4.7,
        reviews: 198,
        experience: '8 Years',
        services: ['Hotel Reservation', 'Resort Booking', 'Group Accommodation'],
        tags: ['Hotel Specialist'],
        startingPrice: 4000,
        avatar: 'SW',
        verified: true,
    },
    {
        id: 19,
        name: 'Gulf Visa Express',
        city: 'Gujranwala',
        coordinates: { lat: 32.1877, lng: 74.1945 },
        rating: 4.5,
        reviews: 231,
        experience: '9 Years',
        services: ['UAE Visa', 'Saudi Visa', 'Oman Visa'],
        tags: ['Visa Expert'],
        startingPrice: 10000,
        avatar: 'GV',
        verified: true,
    },
    {
        id: 20,
        name: 'Maple Leaf Immigration',
        city: 'Lahore',
        coordinates: { lat: 31.5127, lng: 74.3625 },
        rating: 4.8,
        reviews: 356,
        experience: '14 Years',
        services: ['Canada PR', 'Canada Study', 'Canada Work Permit'],
        tags: ['Immigration Expert'],
        startingPrice: 55000,
        avatar: 'ML',
        verified: true,
    },
];

// All available cities
export const cities = [...new Set(agents.map(a => a.city))].sort();

// All available service types
export const serviceTypes = [...new Set(agents.flatMap(a => a.tags))].sort();

// All available services for search matching
export const allServices = [...new Set(agents.flatMap(a => a.services))].sort();

// Default map center (Pakistan)
export const defaultCenter = { lat: 30.3753, lng: 69.3451 };
export const defaultZoom = 6;
